eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 1112
  ssl: 
    key-store: keystore1.p12
    key-store-password: mojpass
    keyStoreType: PKCS12
    key-alias: tomcat1